# -*- coding: utf-8 -*-
"""ml_recommender.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ssXkTl22Y_4VithXj9we6Z0ny8M-ImcX
"""

#  !pip install streamlit
#  !pip install plotly
# pip install -r requirements.txt
# pip install --upgrade pip

import streamlit as st
from PIL import Image
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

# Иконка и заголовок
st.set_page_config(
    page_title="ML Algorithm Recommender",
    page_icon="🧠",
    layout="wide"
)

# Логотип и описание
# col1, col2 = st.columns([1, 4])
# with col1:
#     st.image("https://miro.medium.com/v2/resize:fit:1200/1*Y57k4A2rC1JkUX3x-Cg_TQ.png", width=100)
# with col2:
#     st.title("Рекомендательная система по алгоритмам ML")
#     st.caption("Выберите параметры вашей задачи, и система предложит подходящие алгоритмы с гиперпараметрами")

algorithms_db = {
    # Линейные модели
    "Linear Regression": {
        "task_type": ["regression"],
        "data_size": "any",
        "feature_types": ["numeric"],
        "interpretability": "high",
        "training_speed": "fast",
        "robust_to_noise": "low",
        "handles_missing_data": "no",
        "gpu_support": "no",
        "notes": "Простая и быстрая модель для линейных зависимостей. Чувствительна к выбросам.",
        "hyperparameters": {
            "default": {"fit_intercept": True},
            "tips": "Для мультиколлинеарности добавьте ridge/lasso регуляризацию"
        },
        "documentation": {
            "scikit-learn": "https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LinearRegression.html",
            "concept": "https://scikit-learn.org/stable/modules/linear_model.html#ordinary-least-squares"
        }
    },
    "Logistic Regression": {
        "task_type": ["classification"],
        "data_size": "any",
        "feature_types": ["numeric", "categorical (encoded)"],
        "interpretability": "high",
        "training_speed": "fast",
        "robust_to_noise": "medium",
        "handles_missing_data": "no",
        "gpu_support": "no",
        "notes": "Хорош для бинарной классификации. Требует масштабирования признаков.",
        "hyperparameters": {
            "default": {"C": 1.0, "penalty": "l2", "max_iter": 100},
            "tips": "Уменьшите C для сильной регуляризации. Для несбалансированных классов используйте class_weight='balanced'"
        },
        "documentation": {
            "scikit-learn": "https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html",
            "guide": "https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression"
        }

    },

    # Деревья и ансамбли
    "Decision Tree": {
        "task_type": ["classification", "regression"],
        "data_size": "small-medium",
        "feature_types": ["numeric", "categorical"],
        "interpretability": "high",
        "training_speed": "fast",
        "robust_to_noise": "low",
        "handles_missing_data": "yes",
        "gpu_support": "no",
        "notes": "Склонен к переобучению. Хорош для интерпретируемых решений.",
        "hyperparameters": {
            "default": {
                "criterion": "gini",  # или "entropy" для классификации
                "max_depth": None,
                "min_samples_split": 2
            },
            "important": {
                "max_depth": "Глубина дерева (начните с 3-5 для избежания переобучения)",
                "min_samples_leaf": "Минимальное число образцов в листе (увеличивайте для упрощения модели)",
                "max_features": "Число признаков для разделения ('sqrt' для рандомизированных деревьев)"
            },
            "tips": "Используйте plot_tree() для визуализации решений"
        },
        "documentation": {
            "scikit-learn": "https://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeClassifier.html",
            "visualization": "https://scikit-learn.org/stable/modules/tree.html#tips-on-practical-use"
        }
    },
    "Random Forest": {
        "task_type": ["classification", "regression"],
        "data_size": "medium-large",
        "feature_types": ["numeric", "categorical"],
        "interpretability": "medium",
        "training_speed": "medium",
        "robust_to_noise": "high",
        "handles_missing_data": "yes",
        "gpu_support": "no",
        "notes": "Устойчив к переобучению. Может работать с пропусками.",
         "hyperparameters": {
            "default": {"n_estimators": 100, "max_depth": None},
            "important": {
                "max_depth": "Контролирует переобучение (начните с 5-10)",
                "min_samples_leaf": "Увеличивайте для борьбы с переобучением"
            }
        },
        "documentation": {
            "scikit-learn": "https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html",
            "user guide": "https://scikit-learn.org/stable/modules/ensemble.html#forest"
        }
    },
    "Gradient Boosting (XGBoost/LightGBM/CatBoost)": {
        "task_type": ["classification", "regression"],
        "data_size": "any",
        "feature_types": ["numeric", "categorical"],
        "interpretability": "low",
        "training_speed": "medium (зависит от параметров)",
        "robust_to_noise": "high",
        "handles_missing_data": "yes (особенно CatBoost)",
        "gpu_support": "yes",
        "notes": "Лучшая точность среди ансамблей. Требует настройки гиперпараметров.",
        "hyperparameters": {
            "default": {"n_estimators": 100, "learning_rate": 0.1},
            "tuning_strategy": "Сначала настройте n_estimators и learning_rate, затем max_depth/min_child_weight"
        },
        "documentation": {
            "XGBoost": "https://xgboost.readthedocs.io/",
            "LightGBM": "https://lightgbm.readthedocs.io/",
            "CatBoost": "https://catboost.ai/en/docs/"
        }
    },

    # SVM и ядерные методы
    "SVM": {
        "task_type": ["classification", "regression"],
        "data_size": "small-medium",
        "feature_types": ["numeric"],
        "interpretability": "low",
        "training_speed": "slow",
        "robust_to_noise": "medium",
        "handles_missing_data": "no",
        "gpu_support": "partial (cuML)",
        "notes": "Хорош для малых datasets с чёткими границами. Чувствителен к масштабу данных.",
        "hyperparameters": {
            "default": {
                "C": 1.0,
                "kernel": "rbf",
                "gamma": "scale"
            },
            "important": {
                "C": "Параметр регуляризации (меньше = сильнее регуляризация)",
                "kernel": "Выбор ядра: 'linear', 'poly', 'rbf', 'sigmoid'",
                "gamma": "Влияние отдельного примера ('scale' или 'auto')"
            },
            "tips": "Для больших датасетов используйте LinearSVM"
        },
        "documentation": {
            "scikit-learn": "https://scikit-learn.org/stable/modules/svm.html"
        }
    },

    # Кластеризация
    "K-Means": {
        "task_type": ["clustering"],
        "data_size": "any",
        "feature_types": ["numeric"],
        "interpretability": "medium",
        "training_speed": "fast",
        "robust_to_noise": "low",
        "handles_missing_data": "no",
        "gpu_support": "yes (cuML)",
        "notes": "Требует задания числа кластеров (k). Чувствителен к выбросам.",
        "hyperparameters": {
            "default": {
                "n_clusters": 8,
                "init": "k-means++",
                "n_init": 10
            },
            "important": {
                "n_clusters": "Количество кластеров (используйте elbow method для подбора)",
                "init": "Метод инициализации центроидов ('random' или 'k-means++')"
            },
            "tips": "Всегда масштабируйте данные перед кластеризацией"
        },
        "documentation": {
            "scikit-learn": "https://scikit-learn.org/stable/modules/generated/sklearn.cluster.KMeans.html"
        }
    },
    "DBSCAN": {
        "task_type": ["clustering"],
        "data_size": "small-medium",
        "feature_types": ["numeric"],
        "interpretability": "low",
        "training_speed": "medium",
        "robust_to_noise": "high",
        "handles_missing_data": "no",
        "gpu_support": "partial",
        "notes": "Не требует задания числа кластеров. Хорош для данных с шумом.",
        "hyperparameters": {
            "default": {
                "eps": 0.5,
                "min_samples": 5
            },
            "important": {
                "eps": "Максимальное расстояние между соседями",
                "min_samples": "Минимальное число образцов в кластере"
            },
            "tips": "Хорошо работает для данных с шумом и кластерами разной формы"
        },
        "documentation": {
            "scikit-learn": "https://scikit-learn.org/stable/modules/generated/sklearn.cluster.DBSCAN.html"
        }
    },

    # Нейросети
    "MLP (Neural Network)": {
        "task_type": ["classification", "regression"],
        "data_size": "large",
        "feature_types": ["numeric", "categorical (encoded)"],
        "interpretability": "very low",
        "training_speed": "slow (зависит от архитектуры)",
        "robust_to_noise": "medium",
        "handles_missing_data": "no",
        "gpu_support": "yes",
        "notes": "Универсальный, но требует много данных и настройки.",
        "hyperparameters": {
            "default": {"hidden_layer_sizes": (100,), "activation": "relu"},
            "architecture_tips": "Начинайте с 1-2 слоёв. Используйте BatchNorm и Dropout"
        },
        "documentation": {
            "scikit-learn": "https://scikit-learn.org/stable/modules/generated/sklearn.neural_network.MLPClassifier.html",
            "keras": "https://keras.io/api/layers/core_layers/dense/"
        }
    },
    "CNN (для изображений)": {
        "task_type": ["classification", "regression"],
        "data_size": "very large",
        "feature_types": ["images"],
        "interpretability": "very low",
        "training_speed": "very slow (без GPU почти невозможен)",
        "robust_to_noise": "high",
        "handles_missing_data": "no",
        "gpu_support": "required",
        "notes": "Специализирован для изображений. Требует трансфера обучения на малых данных.",
        "hyperparameters": {
            "default_architecture": "Conv2D(32) -> MaxPooling -> Conv2D(64) -> Flatten -> Dense(128)",
            "transfer_learning": "Используйте предобученные модели (ResNet, EfficientNet)"
        },
        "documentation": {
            "keras": "https://keras.io/api/layers/convolution_layers/convolution2d/",
            "pytorch": "https://pytorch.org/docs/stable/generated/torch.nn.Conv2d.html"
        }
    },
    "RNN/LSTM (для временных рядов и текстов)": {
        "task_type": ["classification", "regression"],
        "data_size": "large",
        "feature_types": ["time_series", "text"],
        "interpretability": "very low",
        "training_speed": "very slow",
        "robust_to_noise": "medium",
        "handles_missing_data": "no",
        "gpu_support": "required",
        "notes": "Для последовательностей (текст, временные ряды). Сложен в настройке.",
        "hyperparameters": {
            "default_architecture": {
                "units": 64,
                "dropout": 0.2,
                "recurrent_dropout": 0.2,
                "batch_size": 32
            },
            "important": {
                "units": "Количество нейронов в LSTM-слое (начните с 32-128)",
                "return_sequences": "True для многослойных RNN",
                "optimizer": "Adam с learning_rate ~0.001"
            },
            "tips": "Используйте Bidirectional LSTM для текстовых задач"
        },
        "documentation": {
            "keras": "https://keras.io/api/layers/recurrent_layers/lstm/",
            "pytorch": "https://pytorch.org/docs/stable/generated/torch.nn.LSTM.html"
        }
    },

    # Для текстов
    "Naive Bayes": {
        "task_type": ["classification"],
        "data_size": "any",
        "feature_types": ["text", "categorical"],
        "interpretability": "high",
        "training_speed": "very fast",
        "robust_to_noise": "medium",
        "handles_missing_data": "yes",
        "gpu_support": "no",
        "notes": "Хорош для текстов и спам-фильтрации. Сильно упрощает предположения.",
        "hyperparameters": {
            "default": {
                "alpha": 1.0,
                "fit_prior": True
            },
            "important": {
                "alpha": "Параметр сглаживания (меньше = сильнее регуляризация)",
                "var_smoothing": "Стабилизация дисперсии (только для GaussianNB)"
            },
            "tips": "MultinomialNB лучше всего подходит для текстовых данных"
        },
        "documentation": {
            "scikit-learn": "https://scikit-learn.org/stable/modules/naive_bayes.html",
            "comparison": "https://scikit-learn.org/stable/modules/naive_bayes.html#comparison-of-naive-bayes-models"
        }
    },
    "Transformer (BERT/GPT)": {
        "task_type": ["classification", "regression"],
        "data_size": "very large",
        "feature_types": ["text"],
        "interpretability": "very low",
        "training_speed": "extremely slow",
        "robust_to_noise": "high",
        "handles_missing_data": "no",
        "gpu_support": "required",
        "notes": "State-of-the-art для NLP. Используйте предобученные модели (например, из Hugging Face).",
        "hyperparameters": {
            "default_pretrained": {
                "model_name": "bert-base-uncased",
                "learning_rate": 2e-5,
                "batch_size": 16
            },
            "important": {
                "max_length": "Максимальная длина входной последовательности (обычно 128-512)",
                "num_train_epochs": "3-5 эпох обычно достаточно для fine-tuning",
                "warmup_steps": "10% от общего числа шагов"
            },
            "tips": "Используйте Hugging Face Transformers с GPU и mixed-precision"
        },
        "documentation": {
            "HuggingFace": "https://huggingface.co/docs/transformers/index",
            "BERT paper": "https://arxiv.org/abs/1810.04805",
            "GPT paper": "https://cdn.openai.com/research-covers/language-unsupervised/language_understanding_paper.pdf"
        }
    }
}

# def get_user_input():
#     """Собирает параметры задачи от пользователя."""
#     print("Опишите вашу задачу машинного обучения:")
#     task_type = input("Тип задачи (classification/regression/clustering): ").strip().lower()
#     data_size = input("Размер данных (small/medium/large/very large): ").strip().lower()
#     feature_types = input("Типы признаков (numeric/categorical/text/images/time_series): ").strip().lower().split(", ")
#     interpretability = input("Важна интерпретируемость? (yes/no): ").strip().lower() == "yes"
#     training_speed = input("Важна скорость обучения? (yes/no): ").strip().lower() == "yes"
#     gpu_available = input("Есть ли GPU? (yes/no): ").strip().lower() == "yes"
#     missing_data = input("Есть ли пропуски в данных? (yes/no): ").strip().lower() == "yes"

#     return {
#         "task_type": task_type,
#         "data_size": data_size,
#         "feature_types": feature_types,
#         "interpretability": interpretability,
#         "training_speed": training_speed,
#         "gpu_available": gpu_available,
#         "missing_data": missing_data
#     }

def recommend_algorithm(user_input, db):
    """Фильтрует и ранжирует алгоритмы."""
    suitable_algorithms = []

    for algo_name, algo_params in db.items():
        # Проверка типа задачи
        if user_input["task_type"] not in algo_params["task_type"]:
            continue

        # Проверка совместимости типов признаков
        compatible_features = True
        for ft in user_input["feature_types"]:
            if ft not in " ".join(algo_params["feature_types"]):
                compatible_features = False
                break
        if not compatible_features:
            continue

        # Проверка других параметров
        if user_input["gpu_available"] and algo_params["gpu_support"] == "no":
            continue
        if user_input["missing_data"] and algo_params["handles_missing_data"] == "no":
            continue

        suitable_algorithms.append((algo_name, algo_params))

    # Сортировка по приоритетам
    if user_input["interpretability"]:
        priority_order = ["high", "medium", "low", "very low"]
        suitable_algorithms.sort(key=lambda x: priority_order.index(x[1]["interpretability"]))
    elif user_input["training_speed"]:
        priority_order = ["very fast", "fast", "medium", "slow", "very slow", "extremely slow"]
        suitable_algorithms.sort(key=lambda x: priority_order.index(x[1]["training_speed"]))

    return suitable_algorithms

# def print_recommendations(recommendations):
#     """Выводит полную информацию об алгоритмах, включая гиперпараметры"""
#     if not recommendations:
#         print("\nНе найдено подходящих алгоритмов. Уточните параметры задачи.")
#         return

#     print("\n=== Рекомендуемые алгоритмы ===")
#     for i, (algo, params) in enumerate(recommendations, 1):
#         print(f"\n{i}. {algo}")
#         print(f"   - Тип задачи: {', '.join(params['task_type'])}")
#         print(f"   - Интерпретируемость: {params['interpretability']}")
#         print(f"   - Скорость обучения: {params['training_speed']}")
#         print(f"   - Поддержка GPU: {params['gpu_support']}")
#         print(f"   - Работа с пропусками: {params['handles_missing_data']}")

#         # Вывод гиперпараметров, если они есть
#         if "hyperparameters" in params:
#             hp = params["hyperparameters"]
#             print(f"\n   Гиперпараметры для {algo}:")

#             if "default" in hp:
#                 print("   - Стандартные значения:", hp["default"])

#             if "important" in hp:
#                 print("   - Ключевые параметры:")
#                 for param, desc in hp["important"].items():
#                     print(f"     * {param}: {desc}")

#             if "tips" in hp:
#                 print("   - Советы:", hp["tips"])

#         # Вывод документации
#         if "documentation" in params:
#             print("\n   Документация:")
#             for name, url in params["documentation"].items():
#                 print(f"     - {name}: {url}")

#         print(f"   - Примечания: {params['notes']}")

# if __name__ == "__main__":
#     print("=== Рекомендательная система по ML-алгоритмам ===")
#     user_input = get_user_input()
#     recommendations = recommend_algorithm(user_input, algorithms_db)
#     print_recommendations(recommendations)

def visualize_algorithm_comparison(recommendations):
    """Создает интерактивные визуализации для сравнения алгоритмов"""
    if not recommendations:
        return

    # Подготовка данных для визуализации
    algo_names = [algo[0] for algo in recommendations]
    params_list = [algo[1] for algo in recommendations]

    # 1. Радиальная диаграмма характеристик
    metrics = ['interpretability', 'training_speed', 'robust_to_noise']
    metric_labels = ['Интерпретируемость', 'Скорость обучения', 'Устойчивость к шуму']

    # Нормализация значений для визуализации
    metric_mapping = {
        'very high': 5, 'high': 4, 'medium': 3, 'low': 2, 'very low': 1,
        'very fast': 5, 'fast': 4, 'medium': 3, 'slow': 2, 'very slow': 1
    }

    fig1 = go.Figure()

    for algo, params in zip(algo_names, params_list):
        values = []
        for metric in metrics:
            value = params.get(metric, 'medium')
            values.append(metric_mapping.get(value.lower(), 3))

        fig1.add_trace(go.Scatterpolar(
            r=values + values[:1],  # Замыкаем круг
            theta=metric_labels + metric_labels[:1],
            fill='toself',
            name=algo
        ))

    fig1.update_layout(
        polar=dict(radialaxis=dict(visible=True, range=[0, 5])),
        showlegend=True,
        title='Сравнение характеристик алгоритмов',
        height=500
    )

    # 2. Гистограмма параметров
    param_data = []
    for algo, params in zip(algo_names, params_list):
        if 'hyperparameters' in params and 'default' in params['hyperparameters']:
            for param, value in params['hyperparameters']['default'].items():
                param_data.append({
                    'Algorithm': algo,
                    'Parameter': param,
                    'Value': str(value)[:50]  # Обрезаем длинные значения
                })

    if param_data:
        df_params = pd.DataFrame(param_data)
        fig2 = px.bar(df_params,
                     x='Algorithm',
                     y='Value',
                     color='Parameter',
                     barmode='group',
                     title='Сравнение гиперпараметров по умолчанию',
                     height=400)
    else:
        fig2 = None

    # 3. Матрица совместимости
    features = set()
    for params in params_list:
        features.update(params.get('feature_types', []))

    feature_matrix = []
    for algo, params in zip(algo_names, params_list):
        row = {'Algorithm': algo}
        for feature in features:
            row[feature] = feature in params.get('feature_types', [])
        feature_matrix.append(row)

    df_features = pd.DataFrame(feature_matrix).set_index('Algorithm')
    fig3 = px.imshow(df_features.T,
                    labels=dict(x="Алгоритм", y="Тип признаков", color="Поддержка"),
                    title="Поддержка типов признаков",
                    color_continuous_scale='Blues')

    return fig1, fig2, fig3

def create_parameter_tuner(params):
    """Создает интерактивные элементы управления для параметров"""
    tuned_params = {}

    if "default" not in params:
        return params

    st.subheader("⚙️ Настройка гиперпараметров")

    for param, default_value in params["default"].items():
        col1, col2 = st.columns([1, 3])

        with col1:
            st.markdown(f"**{param}**")

        with col2:
            param_type = type(default_value)

            if param_type == bool:
                tuned_params[param] = st.checkbox(
                    "", value=default_value, key=param,
                    help=params.get("important", {}).get(param, "")
                )
            elif param_type == int:
                min_val = max(0, default_value - 10) if default_value > 10 else 0
                max_val = default_value + 10
                tuned_params[param] = st.slider(
                    "", min_value=min_val, max_value=max_val,
                    value=default_value, key=param,
                    help=params.get("important", {}).get(param, "")
                )
            elif param_type == float:
                tuned_params[param] = st.number_input(
                    "", value=float(default_value), key=param,
                    help=params.get("important", {}).get(param, ""),
                    step=0.01
                )
            elif param in ["criterion", "penalty", "kernel"]:
                options = {
                    "criterion": ["gini", "entropy"],
                    "penalty": ["l1", "l2", "elasticnet"],
                    "kernel": ["linear", "poly", "rbf", "sigmoid"]
                }
                tuned_params[param] = st.selectbox(
                    "", options.get(param, [default_value]),
                    key=param,
                    help=params.get("important", {}).get(param, "")
                )
            else:
                tuned_params[param] = st.text_input(
                    "", value=str(default_value), key=param,
                    help=params.get("important", {}).get(param, "")
                )

    if "tips" in params:
        st.info(params["tips"])

    return tuned_params

def generate_algorithm_code(algo_name, tuned_params, params):
    """Генерирует готовый Python код для выбранного алгоритма с учетом настроенных параметров"""
    # Базовый шаблон кода
    code_template = {
        "imports": "",
        "data_loading": """
# Загрузка данных
data = pd.read_csv('your_data.csv')
X = data.drop('target', axis=1)
y = data['target']

# Разделение на train/test
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)
""",
        "preprocessing": "",
        "model_init": "",
        "training": "",
        "evaluation": """
# Предсказание и оценка
y_pred = model.predict(X_test)

# Метрики качества
from sklearn.metrics import classification_report, accuracy_score
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\\nClassification Report:\\n", classification_report(y_test, y_pred))
"""
    }

    # Добавляем базовые импорты
    code_template["imports"] = "import pandas as pd\nfrom sklearn.model_selection import train_test_split\n"

    # Обработка разных типов алгоритмов
    if "Linear Regression" in algo_name:
        code_template["imports"] += "from sklearn.linear_model import LinearRegression"
        code_template["model_init"] = f"model = LinearRegression({generate_params(tuned_params)})"
        code_template["evaluation"] = """
from sklearn.metrics import mean_squared_error, r2_score
y_pred = model.predict(X_test)
print("MSE:", mean_squared_error(y_test, y_pred))
print("R2 Score:", r2_score(y_test, y_pred))
"""

    elif "Logistic Regression" in algo_name:
        code_template["imports"] += "from sklearn.linear_model import LogisticRegression"
        code_template["model_init"] = f"model = LogisticRegression({generate_params(tuned_params)})"

    elif "Decision Tree" in algo_name:
        code_template["imports"] += "from sklearn.tree import DecisionTreeClassifier"
        code_template["model_init"] = f"model = DecisionTreeClassifier({generate_params(tuned_params)})"
        code_template["imports"] += "\nfrom sklearn.tree import plot_tree\nimport matplotlib.pyplot as plt"
        code_template["evaluation"] += """
# Визуализация дерева
plt.figure(figsize=(12,8))
plot_tree(model, filled=True, feature_names=X.columns, class_names=True)
plt.show()
"""

    elif "Random Forest" in algo_name:
        code_template["imports"] += "from sklearn.ensemble import RandomForestClassifier"
        code_template["model_init"] = f"model = RandomForestClassifier({generate_params(tuned_params)})"
        code_template["imports"] += "\nimport seaborn as sns"
        code_template["evaluation"] += """
# Важность признаков
feature_imp = pd.Series(model.feature_importances_, index=X.columns).sort_values(ascending=False)
plt.figure(figsize=(10,6))
sns.barplot(x=feature_imp, y=feature_imp.index)
plt.title('Важность признаков')
plt.show()
"""

    elif "XGBoost" in algo_name or "Gradient Boosting" in algo_name:
        code_template["imports"] += "from xgboost import XGBClassifier"
        code_template["model_init"] = f"model = XGBClassifier({generate_params(tuned_params)})"
        code_template["imports"] += "\nfrom xgboost import plot_importance"
        code_template["evaluation"] += """
# Важность признаков XGBoost
plt.figure(figsize=(10,6))
plot_importance(model)
plt.show()
"""

    elif "MLP" in algo_name:
        code_template["imports"] += "from sklearn.neural_network import MLPClassifier"
        code_template["model_init"] = f"model = MLPClassifier({generate_params(tuned_params)})"
        code_template["preprocessing"] = """
# Масштабирование данных для нейросети
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
"""

    elif "CNN" in algo_name:
        code_template["imports"] = """
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
"""
        code_template["model_init"] = """
model = Sequential([
    Conv2D(32, (3, 3), activation='relu', input_shape=(28, 28, 1)),
    MaxPooling2D((2, 2)),
    Conv2D(64, (3, 3), activation='relu'),
    MaxPooling2D((2, 2)),
    Flatten(),
    Dense(64, activation='relu'),
    Dense(10, activation='softmax')
])
"""
        code_template["preprocessing"] = """
# Предобработка изображений
X_train = X_train.reshape(-1, 28, 28, 1) / 255.0
X_test = X_test.reshape(-1, 28, 28, 1) / 255.0
"""
        code_template["training"] = """
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

history = model.fit(X_train, y_train,
                    epochs=10,
                    validation_data=(X_test, y_test))
"""
        code_template["evaluation"] = """
# Графики обучения
plt.plot(history.history['accuracy'], label='Точность на обучении')
plt.plot(history.history['val_accuracy'], label='Точность на валидации')
plt.xlabel('Эпохи')
plt.ylabel('Точность')
plt.legend()
plt.show()
"""

    elif "RNN" in algo_name or "LSTM" in algo_name:
        code_template["imports"] = """
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Embedding
"""
        code_template["model_init"] = f"""
model = Sequential([
    Embedding(input_dim=10000, output_dim=64),
    LSTM({tuned_params.get('units', 64)}),
    Dense(1, activation='sigmoid')
])
"""
        code_template["preprocessing"] = """
# Токенизация текста
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

tokenizer = Tokenizer(num_words=10000)
tokenizer.fit_on_texts(X_train)
X_train = pad_sequences(tokenizer.texts_to_sequences(X_train), maxlen=100)
X_test = pad_sequences(tokenizer.texts_to_sequences(X_test), maxlen=100)
"""
        code_template["training"] = """
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

history = model.fit(X_train, y_train,
                    epochs=5,
                    batch_size=32,
                    validation_data=(X_test, y_test))
"""

    elif "Transformer" in algo_name:
        code_template["imports"] = """
from transformers import pipeline, AutoTokenizer
import torch
"""
        code_template["model_init"] = f"""
model = pipeline('text-classification',
                model='{params["hyperparameters"]["default_pretrained"]["model_name"]}',
                device={0 if params["gpu_support"] == "required" else -1})
"""
        code_template["preprocessing"] = """
# Для трансформеров обычно требуется отдельная токенизация
tokenizer = AutoTokenizer.from_pretrained('bert-base-uncased')
"""

    # Сборка полного кода
    full_code = f"""{code_template['imports']}

{code_template['data_loading']}

{code_template['preprocessing']}

# Инициализация модели
{code_template['model_init']}

# Обучение модели
{code_template['training'] if code_template['training'] else 'model.fit(X_train, y_train)'}

{code_template['evaluation']}
"""

    return full_code

def generate_params(params_dict):
    """Форматирует параметры для строки инициализации модели"""
    return ", ".join([f"{k}={repr(v)}" for k, v in params_dict.items()])

# def generate_algorithm_code(algo_name, tuned_params, params):
#     """Генерирует готовый код Python для выбранного алгоритма"""
#     base_code = {
#         "imports": "",
#         "model_init": "",
#         "training": "",
#         "prediction": ""
#     }

#     # Общие импорты
#     base_code["imports"] = "import pandas as pd\nfrom sklearn.model_selection import train_test_split\n"

#     # Обработка разных типов алгоритмов
#     if "Linear Regression" in algo_name:
#         base_code["imports"] += "from sklearn.linear_model import LinearRegression\n"
#         base_code["model_init"] = f"model = LinearRegression({generate_params(params(tuned_params))})"

#     elif "Logistic Regression" in algo_name:
#         base_code["imports"] += "from sklearn.linear_model import LogisticRegression\n"
#         base_code["model_init"] = f"model = LogisticRegression({generate_params(params(tuned_params))})"

#     elif "Decision Tree" in algo_name:
#         base_code["imports"] += "from sklearn.tree import DecisionTreeClassifier\n"
#         base_code["model_init"] = f"model = DecisionTreeClassifier({generate_params(params(tuned_params))})"

#     elif "Random Forest" in algo_name:
#         base_code["imports"] += "from sklearn.ensemble import RandomForestClassifier\n"
#         base_code["model_init"] = f"model = RandomForestClassifier({generate_params(params(tuned_params))})"

#     elif "XGBoost" in algo_name:
#         base_code["imports"] += "from xgboost import XGBClassifier\n"
#         base_code["model_init"] = f"model = XGBClassifier({generate_params(params(tuned_params))})"

#     elif "MLP" in algo_name:
#         base_code["imports"] += "from sklearn.neural_network import MLPClassifier\n"
#         base_code["model_init"] = f"model = MLPClassifier({generate_params(params(tuned_params))})"

#     elif "Transformer" in algo_name:
#         base_code["imports"] = "from transformers import pipeline\nimport torch\n"
#         base_code["model_init"] = f"model = pipeline('text-classification', model='{params['hyperparameters']['default_pretrained']['model_name']}')"

#     # Общая часть кода
#     base_code["training"] = """
#     # Загрузка данных
#     data = pd.read_csv('your_data.csv')
#     X = data.drop('target', axis=1)
#     y = data['target']

#     # Разделение на train/test
#     X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

#     # Обучение модели
#     model.fit(X_train, y_train)
#     """
#     base_code["prediction"] = """
#     # Предсказание
#     predictions = model.predict(X_test)

#     # Оценка точности
#     accuracy = (predictions == y_test).mean()
#     print(f"Точность модели: {accuracy:.2f}")
#     """

#     # Сборка полного кода
#     full_code = f"{base_code['imports']}\n{base_code['model_init']}\n{base_code['training']}\n{base_code['prediction']}"
#     return full_code

# def generate_params(params_dict):
#     """Форматирует параметры для строки инициализации модели"""
#     return ", ".join([f"{k}={repr(v)}" for k, v in params_dict.items()])

# # Интерфейс Streamlit
# def main():
#     st.title("Рекомендательная система по алгоритмам машинного обучения")
#     st.markdown("""
#     **Как использовать:**
#     1. Укажите параметры вашей задачи в левой панели
#     2. Система предложит подходящие алгоритмы
#     3. Изучите рекомендации и гиперпараметры
#     """)

#     # Сайдбар с параметрами
#     with st.sidebar:
#         st.header("Параметры задачи")
#         task_type = st.selectbox(
#             "Тип задачи",
#             ["classification", "regression", "clustering"]
#         )
#         data_size = st.selectbox(
#             "Размер данных",
#             ["small", "medium", "large", "very large"]
#         )
#         feature_types = st.multiselect(
#             "Типы признаков",
#             ["numeric", "categorical", "text", "images", "time_series"],
#             default=["numeric"]
#         )
#         interpretability = st.checkbox("Важна интерпретируемость модели")
#         training_speed = st.checkbox("Важна скорость обучения")
#         gpu_available = st.checkbox("Доступен GPU")
#         missing_data = st.checkbox("Есть пропуски в данных")

#     user_input = {
#         "task_type": task_type,
#         "data_size": data_size,
#         "feature_types": feature_types,
#         "interpretability": interpretability,
#         "training_speed": training_speed,
#         "gpu_available": gpu_available,
#         "missing_data": missing_data
#     }

#     # Получение рекомендаций
#     recommendations = recommend_algorithm(user_input, algorithms_db)

#     # Отображение результатов
#     st.subheader("Результаты рекомендации")

#     if not recommendations:
#         st.warning("Не найдено подходящих алгоритмов. Попробуйте изменить параметры поиска.")
#     else:
#         for algo, params in recommendations:
#             with st.expander(f"**{algo}**", expanded=False):
#                 st.write(f"**Тип задачи:** {', '.join(params['task_type'])}")
#                 st.write(f"**Интерпретируемость:** {params['interpretability']}")
#                 st.write(f"**Скорость обучения:** {params['training_speed']}")
#                 st.write(f"**Поддержка GPU:** {params['gpu_support']}")
#                 st.write(f"**Работа с пропусками:** {params['handles_missing_data']}")

#                 if "hyperparameters" in params:
#                     hp = params["hyperparameters"]
#                     st.subheader("Гиперпараметры")

#                     if "default" in hp:
#                         st.write("**Стандартные значения:**")
#                         st.code(hp["default"])

#                     if "important" in hp:
#                         st.write("**Ключевые параметры:**")
#                         for param, desc in hp["important"].items():
#                             st.write(f"- `{param}`: {desc}")

#                     if "tips" in hp:
#                         st.info(f"💡 {hp['tips']}")

#                 if "documentation" in params:
#                     st.markdown("**Документация:**")
#                     for name, url in params["documentation"].items():
#                         st.markdown(f"- [{name}]({url})", unsafe_allow_html=True)

#                 st.write(f"**Примечания:** {params['notes']}")

# Интерфейс Streamlit
def main():
    st.title("Рекомендательная система по алгоритмам машинного обучения")
    st.markdown("""
    **Как использовать:**
    1. Укажите параметры вашей задачи в левой панели
    2. Система предложит подходящие алгоритмы
    3. Изучите рекомендации и гиперпараметры
    """)

    # Сайдбар с параметрами
    with st.sidebar:
        st.header("Параметры задачи")
        task_type = st.selectbox(
            "Тип задачи",
            ["classification", "regression", "clustering"]
        )
        data_size = st.selectbox(
            "Размер данных",
            ["small", "medium", "large", "very large"]
        )
        feature_types = st.multiselect(
            "Типы признаков",
            ["numeric", "categorical", "text", "images", "time_series"],
            default=["numeric"]
        )
        interpretability = st.checkbox("Важна интерпретируемость модели")
        training_speed = st.checkbox("Важна скорость обучения")
        gpu_available = st.checkbox("Доступен GPU")
        missing_data = st.checkbox("Есть пропуски в данных")

    user_input = {
        "task_type": task_type,
        "data_size": data_size,
        "feature_types": feature_types,
        "interpretability": interpretability,
        "training_speed": training_speed,
        "gpu_available": gpu_available,
        "missing_data": missing_data
    }

    # Получение рекомендаций
    recommendations = recommend_algorithm(user_input, algorithms_db)

    # Отображение результатов
    st.subheader("Результаты рекомендации")

    if not recommendations:
        st.warning("Не найдено подходящих алгоритмов. Попробуйте изменить параметры поиска.")
    else:
      # Визуализации
        st.subheader("🔍 Визуальное сравнение алгоритмов")
        fig1, fig2, fig3 = visualize_algorithm_comparison(recommendations)

        st.plotly_chart(fig1, use_container_width=True)

        if fig2:
            st.plotly_chart(fig2, use_container_width=True)
        else:
            st.info("Нет данных о гиперпараметрах для визуализации")

        st.plotly_chart(fig3, use_container_width=True)

        # Детали по каждому алгоритму
        st.subheader("📝 Подробная информация по алгоритмам")
        for algo, params in recommendations:
            with st.expander(f"**{algo}**", expanded=False):
                st.write(f"**Тип задачи:** {', '.join(params['task_type'])}")
                st.write(f"**Интерпретируемость:** {params['interpretability']}")
                st.write(f"**Скорость обучения:** {params['training_speed']}")
                st.write(f"**Поддержка GPU:** {params['gpu_support']}")
                st.write(f"**Работа с пропусками:** {params['handles_missing_data']}")

                if "hyperparameters" in params:
                    hp = params["hyperparameters"]
                    st.subheader("Гиперпараметры")

                    if "default" in hp:
                        st.write("**Стандартные значения:**")
                        st.code(hp["default"])

                    if "important" in hp:
                        st.write("**Ключевые параметры:**")
                        for param, desc in hp["important"].items():
                            st.write(f"- `{param}`: {desc}")

                    if "tips" in hp:
                        st.info(f"💡 {hp['tips']}")

                if "documentation" in params:
                    st.markdown("**Документация:**")
                    for name, url in params["documentation"].items():
                        st.markdown(f"- [{name}]({url})", unsafe_allow_html=True)

                st.write(f"**Примечания:** {params['notes']}")

        selected_algo = st.selectbox(
            "Выберите алгоритм для генерации кода:",
            [algo[0] for algo in recommendations],
            index=0
        )

        # Находим выбранный алгоритм
        selected_params = None
        for algo, params in recommendations:
            if algo == selected_algo:
                selected_params = params
                break

        if selected_params:
            with st.expander(f"🔧 Генерация кода для {selected_algo}", expanded=True):
                # Настройка параметров
                if "hyperparameters" in selected_params:
                    tuned_params = create_parameter_tuner(selected_params["hyperparameters"])

                    # Превью изменений
                    st.subheader("Измененные параметры:")
                    st.json(tuned_params)

                    # Генерация кода с новыми параметрами
                    generated_code = generate_algorithm_code(
                        selected_algo,
                        tuned_params,
                        selected_params
                    )
                else:
                    generated_code = generate_algorithm_code(
                        selected_algo,
                        {},
                        selected_params
                    )

                # Отображение кода
                st.subheader("🧑‍💻 Сгенерированный код")
                st.code(generated_code, language='python')

                # Кнопки действий
                col1, col2 = st.columns(2)
                with col1:
                    st.download_button(
                        label="📥 Скачать Python-скрипт",
                        data=generated_code,
                        file_name=f"{selected_algo.lower().replace(' ', '_')}_model.py",
                        mime="text/python"
                    )

                with col2:
                    if st.button("📋 Скопировать код", key="copy_code"):
                        st.session_state.copied = True
                        st.experimental_set_query_params(copy_code=True)

                if st.session_state.get("copied", False):
                    st.success("Код скопирован в буфер обмена!")

                # Инструкции
                st.markdown("""
                **Как использовать:**
                1. Настройте параметры выше (при необходимости)
                2. Скопируйте или скачайте код
                3. Вставьте в ваш проект и замените `your_data.csv`
                4. Дополните предобработку данных при необходимости
                """)

if __name__ == "__main__":
    main()

# Запуск приложения
# Команда для терминала: streamlit run ml_recommender_app.py
